line-length = 100
target-version = "py312"

[lint]
extend-select = ["E", "F", "I"]  # pycodestyle, pyflakes, isort
ignore = ["E501"]  # Let Black handle long lines

[format]
quote-style = "double"
indent-style = "space"

[lint.per-file-ignores]
"core/tests/*" = ["E501"]  # ignore long lines in tests (only if you really want)
