# Generated by Django 5.2.5 on 2025-08-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(unique=True),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["-published_at"], name="core_articl_publish_89e81b_idx"),
        ),
    ]
