# Generated by Django 5.2.5 on 2025-08-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_topic_slug_alter_article_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
