# Generated by Django 5.2.5 on 2025-08-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_source_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='source_name',
        ),
    ]
