# Generated by Django 5.2.5 on 2025-08-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_article_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
